export const CHANGE_TOP_BANNER = 'CHANGE_TOP_BANNER';
export const CHANGE_PLAYLIST_HOT = 'CHANGE_PLAYLIST_HOT';
export const CHANGE_RECOMMEND_LIST = 'CHANGE_RECOMMEND_LIST';
export const CHANGE_NEW_ALBUM = 'CHANGE_NEW_ALBUM';

export const CHANGE_UP_RANKING = "recommend/CHANGE_UP_RANKING";
export const CHANGE_NEW_RANKING = "recommend/CHANGE_New_RANKING";
export const CHANGE_ORIGIN_RANKING = "recommend/CHANGE_ORIGIN_RANKING";
